# Generated by Django 3.2 on 2021-04-14 00:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'HUAWEI'), (2, 'HP'), (3, 'LENOVO'), (4, 'ASUS'), (5, 'MAC')], null=True)),
                ('email', models.CharField(max_length=100)),
                ('comentarios', models.CharField(max_length=1000)),
                ('numeroDocumento', models.IntegerField()),
                ('fecha', models.IntegerField(blank=True, default=None, null=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
